"""Pure lock logic for the ZeAlfie Windows OFFLINE wheelhouse (ZA-WIN-BOOT-02).

The installer (Inno Setup, ``ZeAlfie-Setup.exe``) is fully OFFLINE: the
bundled wheelhouse under ``{app}\\assets\\wheelhouse`` is the ONLY package
source the installer's pip ever sees (``--no-index --find-links``).  This
module owns the EXACT dependency-lock contract
(``packaging/windows/wheelhouse.lock.toml``) that makes that wheelhouse
deterministic:

* :func:`load_lock` parses and validates the committed lock (fail closed —
  a malformed, drifted, or internally inconsistent lock is rejected before
  anything is downloaded);
* :func:`verify_wheelhouse_dir` proves an on-disk wheelhouse directory
  matches the lock EXACTLY (every pinned wheel present, SHA-256 verified,
  no extra files — fail closed on any drift);
* :func:`pinned_download_specs` feeds the deterministic re-download that
  the CI acquisition step performs.

The lock itself is generated by a REAL resolution
(``pip download --platform win_amd64 --python-version 3.13
--only-binary=:all: ...``) — never guessed — and its per-wheel SHA-256
values are computed from the real downloads.  See the lock file header and
``docs/windows-installer.md``.

Design rules (mirror ``provision.py``):

* **pure** — no I/O except reading the lock file and, in
  :func:`verify_wheelhouse_dir`, hashing files on disk; every check has an
  injectable seam for hermetic Linux tests;
* **stdlib-only + the sibling ``provision`` module** (SHA-256 helper) — no
  ZeAlfie import, no third-party import;
* **fail closed** — a typed exception on every inconsistency; there is no
  "best effort" path.
"""

from __future__ import annotations

import ntpath
import os
import re
import tomllib
from dataclasses import dataclass
from pathlib import Path
from typing import Callable

from provision import WindowsBootstrapError, sha256_file

__all__ = [
    "WheelhouseLockError",
    "LockError",
    "WheelhouseVerificationError",
    "WheelEntry",
    "WheelhouseLock",
    "default_lock_path",
    "load_lock",
    "expected_filenames",
    "pinned_filenames",
    "pinned_download_specs",
    "verify_pinned_subset",
    "verify_wheelhouse_dir",
    "zealfie_wheel_filename",
    "parse_wheel_filename",
]

_SHA256_RE = re.compile(r"^[0-9a-f]{64}$")
#: Canonical zealfie wheel filename for a pinned version
#: (``zealfie-0.1.1-py3-none-any.whl``).
_ZEALFIE_WHEEL_RE = re.compile(r"^zealfie-\d+\.\d+\.\d+-py3-none-any\.whl$")


# ---------------------------------------------------------------------------
# Errors (typed, fail closed)
# ---------------------------------------------------------------------------


class WheelhouseLockError(WindowsBootstrapError):
    """Base class for every wheelhouse-lock failure."""


class LockError(WheelhouseLockError):
    """The lock is missing, malformed, or internally inconsistent."""


class WheelhouseVerificationError(WheelhouseLockError):
    """An on-disk wheelhouse does not match the lock exactly."""


# ---------------------------------------------------------------------------
# Lock model
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class WheelEntry:
    """One pinned wheel in the lock.

    ``name``/``version`` are the canonical distribution name and version;
    ``filename`` is the exact wheel filename the download must produce;
    ``sha256`` and ``size`` are recorded from the REAL downloaded file.
    ``sha256`` is ``None`` ONLY for the freshly-built zealfie wheel, whose
    digest is computed by the acquisition step itself (never downloadable).
    """

    name: str
    version: str
    filename: str
    sha256: str | None
    size: int


@dataclass(frozen=True, slots=True)
class WheelhouseLock:
    """Validated content of ``wheelhouse.lock.toml``."""

    zealfie_version: str
    source_commit: str
    platform_tag: str
    python_tag: str
    abi_tag: str
    generated: str
    cpython_version: str
    cpython_installer_sha256: str
    requirements: tuple[str, ...]
    pip_command: str
    zealfie_wheel: WheelEntry
    wheels: tuple[WheelEntry, ...]  # pinned downloadable wheels (sorted)

    def wheel_map(self) -> dict[str, WheelEntry]:
        """``{filename: entry}`` for every pinned downloadable wheel."""
        return {entry.filename: entry for entry in self.wheels}


def default_lock_path() -> Path:
    """Path of ``wheelhouse.lock.toml`` next to this module."""
    return Path(__file__).resolve().parent / "wheelhouse.lock.toml"


def parse_wheel_filename(filename: str) -> tuple[str, str]:
    """Return ``(distribution, version)`` parsed from a wheel filename.

    PEP 427: ``{distribution}-{version}(-{build})?-{python}-{abi}-{platform}.whl``.
    Splits on the FIRST two ``-`` after the version is located from the
    right (the last three hyphen-separated components are
    ``python-abi-platform``).  Raises :class:`LockError` for a filename that
    cannot be a wheel name.
    """
    if not filename.endswith(".whl"):
        raise LockError(f"not a wheel filename: {filename!r}")
    stem = filename[: -len(".whl")]
    # The trailing three fields are python-abi-platform (tags never contain
    # dashes), so splitting from the right by exactly three fields is safe.
    parts = stem.rsplit("-", 3)
    if len(parts) != 4:
        raise LockError(f"cannot parse wheel filename: {filename!r}")
    dist_version, python, abi, platform = parts
    if not python or not abi or not platform:
        raise LockError(f"cannot parse wheel filename: {filename!r}")
    # distribution and version are joined with '-'; distribution itself may
    # contain dashes (e.g. pyproject-hooks).  Split at the FIRST '-'
    # boundary whose remainder starts with a digit: wheel versions are
    # PEP 440 strings and begin with a digit in every real-world case.
    for j, ch in enumerate(dist_version):
        if ch != "-":
            continue
        dist = dist_version[:j]
        version = dist_version[j + 1:]
        if not dist or not version or not version[0].isdigit():
            continue
        if re.fullmatch(r"[A-Za-z0-9_.]+", dist) and re.fullmatch(
            r"[A-Za-z0-9_.!+]+", version
        ):
            return dist, version
    raise LockError(f"cannot parse distribution/version: {dist_version!r}")


def zealfie_wheel_filename(version: str) -> str:
    """Canonical zealfie wheel filename for *version*."""
    return f"zealfie-{version}-py3-none-any.whl"


# ---------------------------------------------------------------------------
# Lock parsing/validation (fail closed)
# ---------------------------------------------------------------------------


def _expect(d: dict, key: str, what: str) -> str:
    value = d.get(key)
    if not isinstance(value, str) or not value.strip():
        raise LockError(f"wheelhouse lock missing/invalid {what}: {key!r}")
    return value.strip()


def _expect_table(d: dict, key: str, what: str) -> dict:
    table = d.get(key)
    if not isinstance(table, dict):
        raise LockError(f"wheelhouse lock missing/invalid {what}: {key!r}")
    return table


def load_lock(path: str | os.PathLike[str] | None = None) -> WheelhouseLock:
    """Load and validate ``wheelhouse.lock.toml`` (fail closed)."""
    lock_path = Path(path) if path is not None else default_lock_path()
    try:
        with open(lock_path, "rb") as fh:
            data = tomllib.load(fh)
    except FileNotFoundError as exc:
        raise LockError(f"wheelhouse lock not found: {lock_path}") from exc
    except (OSError, tomllib.TOMLDecodeError) as exc:
        raise LockError(
            f"wheelhouse lock unreadable/invalid: {lock_path}: {exc}"
        ) from exc

    metadata = _expect_table(data, "metadata", "lock metadata")
    zealfie = _expect_table(data, "zealfie", "[zealfie] wheel")
    wheel_tables = _expect_table(data, "wheel", "[[wheel]] entries")

    zealfie_version = _expect(metadata, "zealfie_version", "zealfie version")
    source_commit = _expect(metadata, "source_commit", "source commit")
    if not re.fullmatch(r"[0-9a-f]{40}", source_commit.lower()):
        raise LockError(
            "wheelhouse lock source_commit must be a full 40-char git "
            f"commit SHA: {source_commit!r}"
        )
    platform_tag = _expect(metadata, "platform_tag", "platform tag")
    python_tag = _expect(metadata, "python_tag", "python tag")
    abi_tag = _expect(metadata, "abi_tag", "abi tag")
    generated = _expect(metadata, "generated", "generation date")
    requirements = metadata.get("requirements")
    if not isinstance(requirements, list) or not requirements:
        raise LockError(
            "wheelhouse lock metadata.requirements must be a non-empty list"
        )
    requirement_tuple = tuple(str(r) for r in requirements)
    pip_command = metadata.get("pip_command")
    if not isinstance(pip_command, str) or not pip_command.strip():
        raise LockError("wheelhouse lock missing metadata.pip_command")

    cpython_version = _expect(metadata, "cpython_version", "cpython version")
    cpython_sha = _expect(
        metadata, "cpython_installer_sha256", "cpython installer sha256"
    ).lower()
    if not _SHA256_RE.match(cpython_sha):
        raise LockError(
            "wheelhouse lock cpython_installer_sha256 is not a 64-char "
            f"lowercase hex digest: {cpython_sha!r}"
        )

    zealfie_filename = _expect(zealfie, "wheel_filename", "zealfie wheel filename")
    expected_filename = zealfie_wheel_filename(zealfie_version)
    if zealfie_filename != expected_filename:
        raise LockError(
            "wheelhouse lock zealfie wheel_filename does not match "
            f"zealfie-<version>: expected {expected_filename!r}, got "
            f"{zealfie_filename!r}"
        )
    zealfie_source = zealfie.get("source", "local-build")
    zealfie_commit = _expect(zealfie, "source_commit", "zealfie source commit")
    if zealfie_commit != source_commit:
        raise LockError(
            "wheelhouse lock [zealfie] source_commit differs from "
            f"metadata.source_commit: {zealfie_commit!r} vs {source_commit!r}"
        )
    # The zealfie wheel is freshly built at acquisition time; its digest is
    # computed then, never pinned (it cannot be downloaded).
    if zealfie.get("sha256") is not None:
        raise LockError(
            "wheelhouse lock [zealfie] must NOT pin a sha256 (the wheel is "
            "built locally at acquisition time)"
        )
    zealfie_entry = WheelEntry(
        name="zealfie",
        version=zealfie_version,
        filename=zealfie_filename,
        sha256=None,
        size=int(zealfie.get("size", 0)) if isinstance(zealfie.get("size"), int) else 0,
    )
    if zealfie_source != "local-build":
        raise LockError(
            f"wheelhouse lock [zealfie] source must be 'local-build', got "
            f"{zealfie_source!r}"
        )

    entries: list[WheelEntry] = []
    seen: set[str] = set()
    for filename, table in wheel_tables.items():
        if not isinstance(table, dict):
            raise LockError(f"wheelhouse lock [wheel.{filename}] is malformed")
        if filename in seen:
            raise LockError(f"wheelhouse lock duplicate wheel entry: {filename}")
        seen.add(filename)
        name = _expect(table, "name", f"wheel {filename} name")
        version = _expect(table, "version", f"wheel {filename} version")
        digest = _expect(table, "sha256", f"wheel {filename} sha256").lower()
        if not _SHA256_RE.match(digest):
            raise LockError(
                f"wheelhouse lock wheel {filename} sha256 is not a 64-char "
                f"lowercase hex digest: {digest!r}"
            )
        size = table.get("size")
        if not isinstance(size, int) or size <= 0:
            raise LockError(f"wheelhouse lock wheel {filename} size invalid: {size!r}")
        parsed_name, parsed_version = parse_wheel_filename(filename)
        if parsed_name.lower().replace("_", "-") != name.lower().replace("_", "-"):
            raise LockError(
                f"wheelhouse lock wheel {filename}: entry name {name!r} does "
                f"not match the filename distribution {parsed_name!r}"
            )
        if parsed_version != version:
            raise LockError(
                f"wheelhouse lock wheel {filename}: entry version {version!r} "
                f"does not match the filename version {parsed_version!r}"
            )
        entries.append(
            WheelEntry(
                name=name, version=version, filename=filename,
                sha256=digest, size=size,
            )
        )

    if not entries:
        raise LockError("wheelhouse lock contains no pinned wheels")
    entries.sort(key=lambda e: e.filename)

    return WheelhouseLock(
        zealfie_version=zealfie_version,
        source_commit=source_commit,
        platform_tag=platform_tag,
        python_tag=python_tag,
        abi_tag=abi_tag,
        generated=generated,
        cpython_version=cpython_version,
        cpython_installer_sha256=cpython_sha,
        requirements=requirement_tuple,
        pip_command=pip_command,
        zealfie_wheel=zealfie_entry,
        wheels=tuple(entries),
    )


def expected_filenames(lock: WheelhouseLock) -> set[str]:
    """Every filename the wheelhouse must contain (incl. the zealfie wheel)."""
    return {e.filename for e in lock.wheels} | {lock.zealfie_wheel.filename}


def pinned_filenames(lock: WheelhouseLock) -> set[str]:
    """Every DOWNLOADABLE pinned filename (excludes the local zealfie wheel)."""
    return {e.filename for e in lock.wheels}


def pinned_download_specs(lock: WheelhouseLock) -> list[str]:
    """Deterministic ``name==version`` download specs from the lock.

    Used with ``pip download --no-deps`` so a later PyPI release can never
    drift the wheelhouse away from the pinned set.
    """
    return [f"{entry.name}=={entry.version}" for entry in lock.wheels]


def _collect_wheels(
    wh_dir: Path, _list_wheels: Callable[[Path], list[Path]] | None
) -> list[Path]:
    """List ``*.whl`` files under *wh_dir* (injectable seam for tests)."""
    if _list_wheels is not None:
        return sorted(_list_wheels(wh_dir))
    if not wh_dir.is_dir():
        raise WheelhouseVerificationError(
            f"wheelhouse directory missing: {wh_dir}"
        )
    return sorted(wh_dir.glob("*.whl"))


def _verify_pinned_hashes(
    wh_dir: Path,
    lock: WheelhouseLock,
    _hash_file: Callable[[Path], str] | None,
) -> int:
    """SHA-256-verify every pinned wheel; returns the summed locked size."""
    total_size = 0
    for entry in lock.wheels:
        path = wh_dir / entry.filename
        if entry.sha256 is not None:
            digest = (
                _hash_file(path)
                if _hash_file is not None
                else sha256_file(path)
            )
            if digest != entry.sha256:
                raise WheelhouseVerificationError(
                    f"wheel SHA-256 mismatch: {entry.filename}: expected "
                    f"{entry.sha256}, computed {digest}"
                )
        total_size += entry.size
    return total_size


def verify_pinned_subset(
    wheelhouse: str | os.PathLike[str],
    lock: WheelhouseLock,
    *,
    _list_wheels: Callable[[Path], list[Path]] | None = None,
    _hash_file: Callable[[Path], str] | None = None,
) -> dict:
    """Verify a download staging dir holds EXACTLY the pinned wheels.

    Used right after ``pip download`` and BEFORE the freshly-built zealfie
    wheel is added: the staging set must equal the pinned set (no missing
    wheel, no extra file, every SHA-256 matching the lock).  Fail closed.
    """
    wh_dir = Path(wheelhouse)
    listing = _collect_wheels(wh_dir, _list_wheels)
    present = {p.name for p in listing}
    expected = pinned_filenames(lock)
    missing = expected - present
    extra = present - expected
    problems: list[str] = []
    if missing:
        problems.append("missing wheels: " + ", ".join(sorted(missing)))
    if extra:
        problems.append("unexpected wheels: " + ", ".join(sorted(extra)))
    if problems:
        raise WheelhouseVerificationError(
            f"staging {wh_dir} does not match the locked wheel set: "
            + "; ".join(problems)
        )
    total_size = _verify_pinned_hashes(wh_dir, lock, _hash_file)
    return {"wheel_count": len(lock.wheels), "total_locked_bytes": total_size}


def verify_wheelhouse_dir(
    wheelhouse: str | os.PathLike[str],
    lock: WheelhouseLock,
    *,
    _list_wheels: Callable[[Path], list[Path]] | None = None,
    _hash_file: Callable[[Path], str] | None = None,
) -> dict:
    """Verify an on-disk wheelhouse matches the lock EXACTLY.

    Checks, fail closed:

    * the directory exists;
    * the set of ``*.whl`` files equals the lock's expected set exactly —
      no missing wheel, no unexpected extra file;
    * every pinned (downloadable) wheel's SHA-256 matches the lock;
    * the freshly-built zealfie wheel is present (its digest is computed by
      the acquisition step, not pinned here).

    ``_list_wheels``/``_hash_file`` are injectable seams for hermetic tests.
    Returns a small summary dict on success.
    """
    wh_dir = Path(wheelhouse)
    listing = _collect_wheels(wh_dir, _list_wheels)
    present = {p.name for p in listing}
    expected = expected_filenames(lock)
    missing = expected - present
    extra = present - expected
    problems: list[str] = []
    if missing:
        problems.append("missing wheels: " + ", ".join(sorted(missing)))
    if extra:
        problems.append("unexpected wheels: " + ", ".join(sorted(extra)))
    if problems:
        raise WheelhouseVerificationError(
            f"wheelhouse {wh_dir} does not match the lock: " + "; ".join(problems)
        )

    total_size = _verify_pinned_hashes(wh_dir, lock, _hash_file)
    return {
        "wheel_count": len(lock.wheels),
        "files": sorted(expected),
        "total_locked_bytes": total_size,
    }
